### ISSUE TITLE
Stale Ids Exception

### ISSUE THREAD

**Issue by dwickwire** [pat/thinking-sphinx#1004]
Hello,

I have a legacy table in which the id is a customer id, it is unique but there can be more than one record with the same id in the table.  There's a pk called `unique_id`.  

So I index using `has :unique_id`, tell the model to have a `self.primary_key = :unique_id` and then I have to add this beauty:
```ruby
class CustomerLocation < LegacyBase
  self.primary_key = :unique_id
  def id
    _read_attribute(:id)
  end
  # ...
end
```

That is because Rails' `id` is a method and not a column which [returns the primary key](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/PrimaryKey.html#method-i-id), the whole "[convention over configuration](http://stackoverflow.com/questions/38824805/odd-orm-behavior-for-rails-query-with-non-id-for-primary-key)" thing.  This little work around helps, but it does not quite work with thinking sphinx.  If I query sphinx on the CLI, I'll get a result, but in Rails I keep getting 0 results, after a stale id retry occurs.  Notice how Sphinx found 1 result.

```sql
irb(main):037:0> pp CustomerLocation.search("joesmith\\@gmail.com")
[  Sphinx Query (25.3ms)  SELECT * FROM `customer_location_core`, `customer_location_partial_core` WHERE MATCH('joesmith\\@gmail.com') AND `sphinx_deleted` = 0 LIMIT 0, 20 OPTION max_matches=1000000
  Sphinx  Found 1 results
  CustomerLocation Load (0.3ms)  SELECT `customer_locations`.* FROM `customer_locations` WHERE `customer_locations`.`unique_id` = 913066
  Sphinx  Stale Ids (2 tries left): 913066
  Sphinx Query (15.4ms)  SELECT * FROM `customer_location_core`, `customer_location_partial_core` WHERE MATCH('joesmith\\@gmail.com') AND `sphinx_deleted` = 0 AND `sphinx_internal_id` NOT IN (913066) LIMIT 0, 20 OPTION max_matches=1000000
  Sphinx  Found 0 results
]
=> []
```

In Sphinx
```sql
$ search -c /opt/data/sphinx/development.sphinx.conf "joesmith\@gmail.com"
Sphinx 2.0.4-id64-release (r3135)
Copyright (c) 2001-2012, Andrew Aksyonoff
Copyright (c) 2008-2012, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/opt/data/sphinx/development.sphinx.conf'...
index 'customer_location_core': query 'joesmith\@gmail.com ': returned 1 matches of 1 total in 0.000 sec

displaying matches:
1. document=5478396, weight=1727, sphinx_internal_id=913066, sphinx_internal_class=CustomerLocation, sphinx_deleted=0, unique_id=913066

words:
1. 'joesmith@gmail.com': 1 documents, 1 hits

```

My index looks like this:
```ruby
ThinkingSphinx::Index.define(:customer_location,
  name: 'customer_location',
  with: :active_record
) do
  indexes :id, as: :gnp_number
  has :unique_id 
  #...
end
```
Is there a way to avoid the stale id?

Note:  If I search with ids_only, I get the correct result.

I'm on Rails 5, ruby 2.3.1 and TS 3.2.0

**Comment by pat** [comment]
Hi Derek,

I'm a little confused as to the situation here… the `unique_id` column is being used by TS as the primary key (which sounds correct), and TS is using `unique_id` values for translating Sphinx results to ActiveRecord objects (also sounds correct). Yet, there doesn't seem to be a corresponding AR object for the unique id in your example (913066)…

So, is 913066 the wrong value? Are you able to share the sql_query from the Sphinx configuration file for the Customer Location source?

**Comment by dwickwire** [comment]
Hi Pat, the `913066` value is the correct pk value, but you know what, after I wrote up this issue I decided to try creating a SQL View and index against that.  It worked magnificently and avoided this problem altogether.  

Now my legacy pk *unique_id* is the `id` and the legacy *id* column is now `customer_id`, which makes life much easier in Rails and the indexing/searching works as expected now.

Anyway, I'm no longer having this issue because of using a SQL View, so I'll close the issue.  Thanks for getting back though.  I just have no idea what really caused the stale IDs.

**Comment by pat** [comment]
Great to know you found a way through that works 😄

**Comment by sesaretah** [comment]
Hi pat,
I have a question regarding this rather old issue, 
I have 
`
class TourPackage < ActiveRecord::Base
  self.primary_key = 'uuid'
  before_create :set_uuid
  def set_uuid
    self.uuid = SecureRandom.uuid
  end

  def id
    self.uuid
  end

  def self.find(uuid)
    TourPackage.find_by_uuid(uuid)
  end
`
and I have an integer_id column which is primary key
`ThinkingSphinx::Index.define :tour_package, :primary_key => :integer_id ,:with => :real_time do
  indexes title
end
`
using `rake ts:rebuild` I get 
`Generating configuration to /home/hosein/Projects/tours/config/development.sphinx.conf
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/home/hosein/Projects/tours/config/development.sphinx.conf'...
listening on 127.0.0.1:9306
precaching index 'tour_package_core'
precached 1 indexes in 0.000 sec
Started searchd successfully (pid: 21490).
Generating index files for tour_package_core
rake aborted!
TypeError: no implicit conversion of Integer into String

Tasks: TOP => ts:rebuild => ts:rt:index
(See full trace by running task with --trace)
`

**Comment by pat** [comment]
@sesaretah can you provide the full stack-trace from the rake task by running `rake ts:rebuild --trace`?

**Comment by sesaretah** [comment]
sure
```
rake ts:rebuild --trace** Invoke ts:rebuild (first_time)
** Invoke ts:stop (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute ts:stop
searchd is not currently running.
** Invoke ts:clear (first_time)
** Invoke ts:sql:clear (first_time)
** Invoke environment 
** Execute ts:sql:clear
============= WARNING FROM mysql2 =============
The options :user, :pass, :hostname, :dbname, :db, and :sock will be deprecated at some point in the future.
Instead, please use :username, :password, :host, :port, :database, :socket, :flags for the options.
============= END WARNING FROM mysql2 =========
** Invoke ts:rt:clear (first_time)
** Invoke environment 
** Execute ts:rt:clear
** Execute ts:clear
** Invoke ts:configure (first_time)
** Invoke environment 
** Execute ts:configure
Generating configuration to /home/hosein/Projects/tours/config/development.sphinx.conf
** Invoke ts:sql:index (first_time)
** Invoke environment 
** Execute ts:sql:index
** Invoke ts:start (first_time)
** Invoke environment 
** Execute ts:start
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/home/hosein/Projects/tours/config/development.sphinx.conf'...
listening on 127.0.0.1:9306
precaching index 'tour_package_core'
precached 1 indexes in 0.000 sec
Started searchd successfully (pid: 12315).
** Invoke ts:rt:index (first_time)
** Invoke environment 
** Execute ts:rt:index
Generating index files for tour_package_core
rake aborted!
TypeError: no implicit conversion of Integer into String
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/core/index.rb:37:in `+'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/core/index.rb:37:in `document_id_for_key'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/transcribe_instance.rb:27:in `document_id'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/transcribe_instance.rb:13:in `call'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/transcribe_instance.rb:5:in `call'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/transcriber.rb:17:in `block in copy'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/transcriber.rb:15:in `each'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/transcriber.rb:15:in `copy'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/populator.rb:16:in `block in populate'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/querying.rb:9:in `find_in_batches'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/populator.rb:15:in `populate'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/real_time/populator.rb:5:in `populate'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/commands/index_real_time.rb:6:in `block in call'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/commands/index_real_time.rb:5:in `each'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/commands/index_real_time.rb:5:in `call'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/commands/base.rb:11:in `call_with_handling'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/commands/base.rb:7:in `call'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/commander.rb:7:in `call'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/interfaces/base.rb:9:in `command'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/interfaces/real_time.rb:26:in `index'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/tasks.rb:68:in `block (3 levels) in <top (required)>'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/hosein/.rbenv/versions/2.5.1/bin/rake:23:in `load'
/home/hosein/.rbenv/versions/2.5.1/bin/rake:23:in `<main>'
Tasks: TOP => ts:rebuild => ts:rt:index
```

**Comment by pat** [comment]
Right, sounds like a bug to me! I'll try to get it fixed this evening.

**Comment by pat** [comment]
@sesaretah I've just pushed a fix to the develop branch - if you're able to test it and confirm it works for you, that'd be great, and then I can publish a new gem release.

```ruby
gem "thinking-sphinx", "~> 4.0",
  :git    => "https://github.com/pat/thinking-sphinx.git",
  :branch => "develop"
```

**Comment by sesaretah** [comment]
Great. It works like a charm.

**Comment by pat** [comment]
Excellent, thanks for the confirmation :) I've just released v4.1.0 with the fix.

**Comment by sesaretah** [comment]
I am also having trouble destroying objects:
```
Loading development environment (Rails 4.2.8)
irb(main):002:0> TourPackage.first.destroy
  TourPackage Load (1.1ms)  SELECT  `tour_packages`.* FROM `tour_packages`  ORDER BY `tour_packages`.`uuid` ASC LIMIT 1
   (0.4ms)  BEGIN
  SQL (2.1ms)  DELETE FROM `tour_packages` WHERE `tour_packages`.`uuid` = 'b5b0ea17-3bf8-43a9-99bc-35b281559043'
   (3.8ms)  ROLLBACK
Traceback (most recent call last):
       16: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:506:in `block in call'
       15: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
       14: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:455:in `block in make_lambda'
       13: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:455:in `public_send'
       12: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/callbacks.rb:9:in `block (2 levels) in callbacks'
       11: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/active_record/callbacks/delete_callbacks.rb:9:in `after_destroy'
       10: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/active_record/callbacks/delete_callbacks.rb:21:in `delete_from_sphinx'
        9: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/active_record/callbacks/delete_callbacks.rb:21:in `each'
        8: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/active_record/callbacks/delete_callbacks.rb:22:in `block in delete_from_sphinx'
        7: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/deletion.rb:12:in `perform'
        6: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/deletion.rb:43:in `perform'
        5: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/deletion.rb:26:in `document_ids_for_keys'
        4: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/deletion.rb:26:in `collect'
        3: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/deletion.rb:26:in `block in document_ids_for_keys'
        2: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/core/index.rb:37:in `document_id_for_key'
        1: from /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thinking-sphinx-4.1.0/lib/thinking_sphinx/core/index.rb:37:in `+'
TypeError (no implicit conversion of Integer into String)
```

**Comment by sesaretah** [comment]
There is also an error  regarding `after_save ThinkingSphinx::RealTime.callback_for` as follows:
```
Started POST "/tour_packages" for 127.0.0.1 at 2018-12-29 14:22:16 +0330
Processing by TourPackagesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"yh2II1PSFSno2....dwfSdjfqlViFjkFiaBkX1iIqBOQH8ZJnYi6wYFjgabszM1bH44M4Q==", "tour_package"=>{"title"=>"Ankara", "days"=>"", "nights"=>"", "details"=>""}}
   (0.2ms)  BEGIN
  SQL (1.5ms)  INSERT INTO `tour_packages` (`title`, `details`, `created_at`, `updated_at`, `rank`, `uuid`) VALUES ('Ankara', '', '2018-12-29 10:52:16', '2018-12-29 10:52:16', 0, 'e34affb7-4e42-40ac-9bf7-d6ad464c6b9b')
  Sphinx Query (4.9ms)  REPLACE INTO tour_package_core (id, `title`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`) VALUES (, 'Ankara', 0, 'TourPackage', 0)
   (2.9ms)  ROLLBACK
Completed 500 Internal Server Error in 18ms (ActiveRecord: 4.6ms)

ThinkingSphinx::SyntaxError (sphinxql: syntax error, unexpected ',' near ', 'Ankara', 0, 'TourPackage', 0)' - REPLACE INTO tour_package_core (id, `title`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`) VALUES (, 'Ankara', 0, 'TourPackage', 0)):
  app/controllers/tour_packages_controller.rb:52:in `block in create'
  app/controllers/tour_packages_controller.rb:51:in `create'


  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.3ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.3ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (22.9ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (1.1ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.5ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (18.6ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.5ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.6ms)
  Rendered /home/hosein/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (39.2ms)

```

**Comment by pat** [comment]
Okay, I had a more detailed look through the codebase, I think I've got all the cases covered for alternative primary key use (both with real-time indices and generally). If you could try the develop branch again to confirm, that'd be great.

Also, I got a few email notifications about comments here, which you've cleaned up - just wondering if there were still any issues with instance updates, not just deletions?
