### ISSUE TITLE
Difficulties configuring Sphinx on a production server

### ISSUE THREAD

**Issue by ben-eb** [pat/thinking-sphinx#1047]
Ref: https://github.com/pat/thinking-sphinx/issues/431#issuecomment-277843996

In development, the configuration is generated correctly but I'm getting this error in production:

```
$ RAILS_ENV=production SPHINX_VERSION=2.2.11 bundle exec rake ts:index
Generating configuration to /home/app/shared/production.sphinx.conf
rake aborted!
Riddle::Configuration::ConfigurationError: Riddle::Configuration::ConfigurationError
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration/source.rb:7:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/active_record/sql_source.rb:71:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration/index.rb:29:in `block in render'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration/index.rb:29:in `collect'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration/index.rb:29:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/core/index.rb:57:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration.rb:43:in `block in render'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration.rb:43:in `collect'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration.rb:43:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/configuration.rb:102:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/configuration.rb:108:in `block in render_to_file'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/configuration.rb:108:in `render_to_file'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/rake_interface.rb:30:in `configure'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/rake_interface.rb:41:in `index'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/tasks.rb:9:in `block (2 levels) in <top (required)>'
/home/app/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
/home/app/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
Tasks: TOP => ts:index
(See full trace by running task with --trace)
```

My indices are:

```ruby
# app/indices/company_index.rb
ThinkingSphinx::Index.define :company, with: :active_record do
  # Search companies on addresses
  join addresses

  indexes addresses.line1, as: :address_line1
  indexes addresses.line2, as: :address_line2
  indexes addresses.city, as: :address_city
  indexes addresses.state, as: :address_state
  indexes addresses.zip, as: :address_zip

  # Geodistance
  has 'RADIANS(addresses.latitude)',  as: :lat, type: :float
  has 'RADIANS(addresses.longitude)', as: :lng, type: :float
  group_by 'lat', 'lng'

  # Timestamps
  has created_at, updated_at
end

# app/indices/property_index.rb
ThinkingSphinx::Index.define :property, with: :active_record do
  # Search properties on addresses
  join addresses

  indexes addresses.line1, as: :address_line1
  indexes addresses.line2, as: :address_line2
  indexes addresses.city, as: :address_city
  indexes addresses.state, as: :address_state
  indexes addresses.zip, as: :address_zip

  # Geodistance
  has 'RADIANS(addresses.latitude)',  as: :lat, type: :float
  has 'RADIANS(addresses.longitude)', as: :lng, type: :float
  group_by 'lat', 'lng'

  # Search properties on features
  PropertyFeatures.new.attributes.keys.each do |key|
    if key == :property_owner
      has "features -> '#{key}'", type: :string, as: key.to_sym
    else
      has "features -> '#{key}'", type: :integer, as: key.to_sym
    end
  end

  # Search properties on description/key features
  indexes description
  indexes key_features

  # Category => house, flat etc
  indexes category

  # Timestamps
  has created_at, updated_at, expires_at, featured_expires_at, marketed_expires_at
end
```

The `PropertyFeatures` model is a simple class for loading values from Postgresql's hstore extension:

```ruby
class PropertyFeatures
  include Virtus.model

  attribute :asking_price, Integer
  attribute :bathrooms, Integer
  attribute :bedrooms, Integer
  attribute :deposit, Integer
  attribute :floors, Integer
  attribute :monthly_rent, Integer
  attribute :property_owner, String
  attribute :unit_size, Integer

  def self.dump(preferences)
    preferences.to_hash
  end

  def self.load(preferences)
    new(preferences)
  end
end
```

If you need any further details I would be happy to provide them. Thanks in advance!

**Comment by pat** [comment]
Thanks Ben for all of those details. I'm wondering if there's a difference between how you specify databases for each environment? Is development via the more specific parameters, but production with a URL?

**Comment by ben-eb** [comment]
Right now I'm using `config/database.yml` to set the details:

```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: app
  username: app
  password:

production:
  <<: *default
  database: app
  username: app
  password: <%= ENV["PG_USER_PASSWORD"] %>
```

Where `ENV` is managed via https://github.com/bkeepers/dotenv.

**Comment by pat** [comment]
Huh, well that's annoying. There's definitely a difference between the two environments, I'm just not sure what it is! Certainly doesn't seem to be your database setup. And from what I can see, `PropertyFeatures.new.attributes.keys` will be the same in both environments as well. Is your production database at the same migration point as your development one?

Although, just to be clear (because the error most definitely isn't), the configuration error is because of one of these things:

* An index source doesn't have a name,
* An index source doesn't have a type,
* An index source doesn't have a database host/user/database/query (or isn't inherited).

Thinking Sphinx automatically creates sources for each index (as you'll note in your development Sphinx configuration file), and it should be covering off all of those settings. The one setting that's missing from both environments is the database host (sql_host in Sphinx), but Thinking Sphinx defaults that to localhost, so that *really* shouldn't be the issue.

It's midnight here, so I'm going to sleep on this and see if any inspiration appears in the morning, but right now I'm at a complete loss as to what the cause of the problem is.

**Comment by ben-eb** [comment]
Yeah, the migration points are the same; I ran this from scratch the other day to make sure it wasn't causing an issue! I'll check with my host and see if it's the inherited configuration that's causing issues. Thank you for your input. 😃

**Comment by ben-eb** [comment]
Hi @pat,

I believe I resolved this issue, for some reason the deploy was not loading the password for the pg database correctly, so it wasn't authenticated! I've resolved this and now I can configure/index as normal.

Thanks for leading me in the right direction! 🎉

**Comment by pat** [comment]
Great to hear you've got it working :)
