### ISSUE TITLE
rake ts:start NODETACH=true not working

### ISSUE THREAD

**Issue by hennevogel** [pat/thinking-sphinx#1049]
When using 3.3.0 
```
vagrant@vagrant-openSUSE-Leap:/vagrant/src/api> grep thinking Gemfile*
Gemfile:gem 'thinking-sphinx', '>= 3.3.0'
Gemfile.lock:    thinking-sphinx (3.3.0)
Gemfile.lock:  thinking-sphinx (>= 3.3.0)
```
to start in foreground I get this trace:
```
vagrant@vagrant-openSUSE-Leap:/vagrant/src/api> bundle exec rake ts:start NODETACH=true --trace
** Invoke ts:start (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute ts:start
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/vagrant/src/api/config/development.sphinx.conf'...
listening on 127.0.0.1:9306
precaching index 'package_core'
precaching index 'project_core'                             
precached 2 indexes in 0.025 sec                            
rake aborted!
TypeError: no implicit conversion from nil to integer
/usr/lib64/ruby/gems/2.4.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/rake_interface.rb:134:in `wait'
/usr/lib64/ruby/gems/2.4.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/rake_interface.rb:134:in `start_attached'
/usr/lib64/ruby/gems/2.4.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/rake_interface.rb:65:in `start'
/usr/lib64/ruby/gems/2.4.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/tasks.rb:39:in `block (2 levels) in <top (required)>'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/bin/rake:22:in `load'
/usr/bin/rake:22:in `<top (required)>'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/bin/bundle:22:in `load'
/usr/bin/bundle:22:in `<main>'
Tasks: TOP => ts:start
```

**Comment by pat** [comment]
Just pushed a fix to the develop branch for this. If you could give it a spin and confirm it's working well for you, that'd be great :)

```ruby
gem 'thinking-sphinx', '>= 3.3.0',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => '22db6bff3a'
```

**Comment by hennevogel** [comment]
Working fine, thanks for the fix @pat 💐
