### ISSUE TITLE
Issue with dollar sign

### ISSUE THREAD

**Issue by ghost** [pat/thinking-sphinx#235]
Hi,

I have a problem when making searches that include the dollar sign character, the exception I get is the following:

```
ThinkingSphinx::SphinxError: index inquiry_core,room_core,user_core: syntax error, unexpected '$' near '$'
[GEM_ROOT]/bundler/gems/thinking-sphinx-6259635e2692/lib/thinking_sphinx/search.rb:406:in `block in populate'
[GEM_ROOT]/bundler/gems/thinking-sphinx-6259635e2692/lib/thinking_sphinx/search.rb:551:in `call'
[GEM_ROOT]/bundler/gems/thinking-sphinx-6259635e2692/lib/thinking_sphinx/search.rb:551:in `retry_on_stale_index'
[GEM_ROOT]/bundler/gems/thinking-sphinx-6259635e2692/lib/thinking_sphinx/search.rb:394:in `populate'
[GEM_ROOT]/bundler/gems/thinking-sphinx-6259635e2692/lib/thinking_sphinx/search.rb:176:in `method_missing'
app/views/admin/searches/create.html.erb:4:in `_app_views_admin_searches_create_html_erb__932742353_105545480__302590324'
```

Any clue what the reason could be?

**Comment by vibhoo** [comment]
Please update the url it's now on 
https://github.com/pat/thinking-sphinx/issues/235
