### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by ulitiy** [pat/thinking-sphinx#262]
I'm sorry, maybe it isn't a ts bug, but I don't know how to solve this problem and an exception is raised only if I try to use ts. In ruby 1.8.7 everything was OK.
Exception is raised when I try to render partial with ts results.
I asked the question here
http://stackoverflow.com/questions/6892268/incompatible-character-encodings-utf-8-and-ascii-8bit-and-thinking-sphinx

**Comment by xtrasimplicity** [comment]
Sorry for re-opening this issue, but I'm currently experiencing this issue in TS 3.4.2 with Riddle 2.3.0, when using realtime indices. It looks like the issue may be that one of the objects stored in the database contains foreign characters?

The stacktrace:
```
2018-01-18T03:45:46.268120579Z app[thinking_sphinx.1]: thinking_sphinx| ........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................  Publication Load (7.0ms)  SELECT `publications`.* FROM `publications` WHERE (`publications`.`id` > 2071) ORDER BY `publications`.`id` ASC LIMIT 1000
2018-01-18T03:45:47.389576699Z app[thinking_sphinx.1]: rake aborted!
2018-01-18T03:45:47.389611856Z app[thinking_sphinx.1]: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
2018-01-18T03:45:47.390155836Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/riddle-2.3.0/lib/riddle/query/insert.rb:36:in `join'
2018-01-18T03:45:47.390164849Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/riddle-2.3.0/lib/riddle/query/insert.rb:36:in `values_to_s'
2018-01-18T03:45:47.390168384Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/riddle-2.3.0/lib/riddle/query/insert.rb:19:in `to_sql'
2018-01-18T03:45:47.390173059Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/real_time/transcriber.rb:17:in `copy'
2018-01-18T03:45:47.390176538Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/real_time/populator.rb:14:in `block in populate'
2018-01-18T03:45:47.390179967Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation/batches.rb:72:in `find_in_batches'
2018-01-18T03:45:47.390183794Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/querying.rb:8:in `find_in_batches'
2018-01-18T03:45:47.390187096Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/real_time/populator.rb:13:in `populate'
2018-01-18T03:45:47.390190462Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/real_time/populator.rb:3:in `populate'
2018-01-18T03:45:47.390206594Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/interfaces/real_time.rb:25:in `block in index'
2018-01-18T03:45:47.390210128Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/interfaces/real_time.rb:25:in `each'
2018-01-18T03:45:47.390213464Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/interfaces/real_time.rb:25:in `index'
2018-01-18T03:45:47.390217409Z app[thinking_sphinx.1]: /app/vendor/bundle/ruby/1.9.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/tasks.rb:101:in `block (3 levels) in <top (required)>'
2018-01-18T03:45:47.390221558Z app[thinking_sphinx.1]: /app/lib/tasks/sphinx.rake:6:in `block (2 levels) in <top (required)>'
2018-01-18T03:45:47.390224988Z app[thinking_sphinx.1]: Tasks: TOP => ts:index => ts:rt:index
2018-01-18T03:45:47.390229004Z app[thinking_sphinx.1]: (See full trace by running task with --trace)
2018-01-18T03:45:47.452506464Z app[thinking_sphinx.1]: SIGINT received
2018-01-18T03:45:47.452536517Z app[thinking_sphinx.1]: sending SIGTERM to all processes
```
I'm thinking that perhaps I might be able to override a method somewhere in the `Publications` model, to convert ASCII-8BIT characters into UTF8, but I'm not sure which method. Any suggestions?

Thanks so much!

**Comment by pat** [comment]
No need to apologise @xtrasimplicity!

I guess the first place I'd start is looking at the Rails logs to see if that gives you some idea of which objects could be involved in providing non-UTF8 data? The catch is that TS batches results. Maybe reducing the batch size would help with the hunting? You can set `batch_size` per environment within `config/thinking_sphinx.yml`.

If you've got this data in a local environment where you can debug more directly, you could try removing fields from your index and then running `ts:index` until you find the one that's the source of the problem. Then, in a Rails console try to determine which records have non-UTF8 data?

**Comment by xtrasimplicity** [comment]
Thanks for your incredibly prompt response, @pat, it's greatly appreciated! :)
I temporarily monkey patched `Riddle::Query::Insert` to make `translated_value()` force encoding, which fixed my issue. I don't believe the content itself was really an issue.

```
class Riddle::Query::Insert
  alias_method :original_translated_value, :translated_value
  
  def translated_value(value)
    val = original_translated_value(value)

    if val.is_a? String
      val = val.force_encoding('UTF-8')
    end
  
    val
  end
end
```

I've submitted a PR on the riddle project, here: https://github.com/pat/riddle/pull/102

Thanks once again!
