### ISSUE TITLE
Connection::MRI#query_all doesn't split results properly

### ISSUE THREAD

**Issue by timriley** [pat/thinking-sphinx#408]
I'm using these versions of thinking sphinx and mysql2:

``` ruby
gem "mysql2", "0.3.12b4"
gem "thinking-sphinx", "~> 3.0.0"
```

I can successfully create an index, but when I tried a search, I got errors like this:

```
>> Post.search("coffee").first

NoMethodError: undefined method `inject' for nil:NilClass
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/middlewares/inquirer.rb:49:in `call'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/middlewares/inquirer.rb:14:in `block in call'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/middlewares/inquirer.rb:13:in `each'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/middlewares/inquirer.rb:13:in `call'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/middlewares/geographer.rb:9:in `call'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/middlewares/sphinxql.rb:11:in `call'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/middlewares/stale_id_filter.rb:10:in `call'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/search.rb:58:in `populate'
    from /Users/tim/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thinking-sphinx-3.0.0/lib/thinking_sphinx/search.rb:99:in `method_missing'
```

It turns out that `Connection::MRI#query_all` wasn't handling the two queries from `BatchInquirer` properly. `BatchInquirer` was calling `append_query` with `context[:sphinxql].to_sql` and `Riddle::Query.meta` properly, but when `ThinkingSphinx::Middlewares::Inquirer#call` ran `batch.results`, it was getting an array back with only one `Mysql2::Result`, instead of two. This meant that  `Inner.new(context).call batch.results[index], batch.results[index + 1]` was passing `nil` as the second argument and causing the "undefined method" errors.

I was able to make things work again with this monkey-patch inside my app:

``` ruby
module ThinkingSphinx
  module Connection
    class MRI
      def query_all(*statements)
        statements.map { |statement| client.query(statement) }
      end
    end
  end
end
```

That's less efficient than your current approach, because it results in two queries, but at this point, at least it's giving me two results back, which means I can actually run searches with TS3 now.

Any ideas what might be happening?

**Comment by andreazaupa** [comment]
It work for me too!
If you have both postgres and mysql installed, the sphinx recipe chose postgres.
