### ISSUE TITLE
Riddle::Configuration::ConfigurationError in Windows

### ISSUE THREAD

**Issue by dheenaINDIAN** [pat/thinking-sphinx#431]
I am using thinking-sphinx - 3.0.0
i am using Windows
i have created index folder

when i give rake ts:index, it throws error as 

Generating configuration to C:/project/SybrantLive/config/development.sphinx.conf
rake aborted!
Riddle::Configuration::ConfigurationError

help me to fix it!

**Comment by kveerababu-nyros** [comment]
rake ts:index
Generating configuration to /home/nyros/Desktop/rails-bootstrap/config/development.sphinx.conf
sh: 1: indexer: not found

**Comment by pat** [comment]
@kveerababu-nyros have you installed Sphinx on your machine? From your path, it sounds like you're on a Mac: http://freelancing-gods.com/thinking-sphinx/installing_sphinx/mac.html

**Comment by ben-eb** [comment]
@pat I'm also getting a similar error:

```
$ RAILS_ENV=production SPHINX_VERSION=2.2.11 bundle exec rake ts:index
Generating configuration to /home/app/shared/production.sphinx.conf
rake aborted!
Riddle::Configuration::ConfigurationError: Riddle::Configuration::ConfigurationError
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration/source.rb:7:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/active_record/sql_source.rb:71:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration/index.rb:29:in `block in render'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration/index.rb:29:in `collect'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration/index.rb:29:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/core/index.rb:57:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration.rb:43:in `block in render'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration.rb:43:in `collect'
/home/app/shared/bundle/ruby/2.2.0/gems/riddle-2.1.0/lib/riddle/configuration.rb:43:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/configuration.rb:102:in `render'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/configuration.rb:108:in `block in render_to_file'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/configuration.rb:108:in `render_to_file'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/rake_interface.rb:30:in `configure'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/rake_interface.rb:41:in `index'
/home/app/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/tasks.rb:9:in `block (2 levels) in <top (required)>'
/home/app/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
/home/app/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
Tasks: TOP => ts:index
(See full trace by running task with --trace)
```

My configuration is as follows:

```yml
production:
  pid_file: /home/app/shared/tmp/searchd.pid
  indices_location: /home/app/shared/db/sphinx
  configuration_file: /home/app/shared/production.sphinx.conf
  binlog_path: /home/app/shared/binlog
  bin_path: /usr/bin
  mysql41: 9312
  enable_star: true
  min_infix_len: 3
```

Any advice would be greatly appreciated!

**Comment by pat** [comment]
Hi Ben

Can you share your index definitions? Looks like the issue might be related to them. Also: probably worth putting this in a new issue :)
