### ISSUE TITLE
Multi core configuration

### ISSUE THREAD

**Issue by pioz** [pat/thinking-sphinx#441]
Hi, there is a way (like `sphinx.yml` conf file) to generate a configuration file (`production.sphinx.conf`) to allow Sphinx to use all available processor cores?

Example here http://nerds.airbnb.com/how-we-improved-search-performance-by-2x

**Comment by jogaco** [comment]
I am stuck trying to generate config for several threads:

```
4.times do |index|
  ThinkingSphinx::Index.define "model_#{index}", :with => :active_record, :delta => ThinkingSphinx::Deltas::ResqueDelta do
    indexes name, :sortable => true
    ...
    where "id % #{index}"
  end
end
```

I get this error when running rake ts:configure

```
NameError: uninitialized constant Model0
/home/user/.rvm/gems/ruby-2.1.3@project/gems/activesupport-3.2.18/lib/active_support/inflector/methods.rb:230:in `block in constantize'
/home/user/.rvm/gems/ruby-2.1.3@project/gems/activesupport-3.2.18/lib/active_support/inflector/methods.rb:229:in `each'
/home/user/.rvm/gems/ruby-2.1.3@project/gems/activesupport-3.2.18/lib/active_support/inflector/methods.rb:229:in `constantize'
/home/user/.rvm/gems/ruby-2.1.3@project/gems/activesupport-3.2.18/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
/home/user/.rvm/gems/ruby-2.1.3@project/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/core/index.rb:43:in `model'
/home/user/.rvm/gems/ruby-2.1.3@project/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/active_record/index.rb:9:in `append_source'
/home/user/.rvm/gems/ruby-2.1.3@project/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/active_record/interpreter.rb:64:in `__source'
/home/user/.rvm/gems/ruby-2.1.3@project/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/active_record/interpreter.rb:20:in `indexes'
```

Any help would be appreciated.

**Comment by pat** [comment]
With TS v3, the first argument of `ThinkingSphinx::Index.define` must be a lowercase/underscored representation of the model. If you want to specify a custom name, then use the `:name` option:

```ruby
ThinkingSphinx::Index.define(:model,
  :name  => "model_#{index}",
  :with  => :active_record,
  :delta => ThinkingSphinx::Deltas::ResqueDelta
) do
  # ...
end
```

**Comment by andrewroth** [comment]
Hi Pat, I'm trying to get this set up for one of my projects.  I'm getting "no enabled local indexes to search" .. do you know what that means?  and anything I can do to debug it?

**Comment by pat** [comment]
Hi Andrew - can you share the index definitions you've got?
