### ISSUE TITLE
undefined method `fields' for #<Vlad::Subversion:xxxx>

### ISSUE THREAD

**Issue by nimeshnikum** [pat/thinking-sphinx#809]
Ruby 2.0.0
Rails 4.1.1
thinking-sphinx 3.1.1
vlad 2.6.3

When I use vlad to deploy my application, thinking sphinx breaks and doesn't allow to configure or index. Following is the error I am getting:

``` ruby
rake aborted!
NoMethodError: undefined method `fields' for #<Vlad::Git:0xa17d89c>
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/statement.rb:67:in `field_presenters'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/statement.rb:118:in `select_clause'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/statement.rb:89:in `scope_by_select'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/statement.rb:54:in `filter_by_scopes'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/statement.rb:12:in `to_relation'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder.rb:11:in `sql_query'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_source.rb:119:in `build_sql_query'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_source.rb:136:in `prepare_for_render'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_source.rb:65:in `render'
~/.rvm/gems/ruby-2.0.0-p451/gems/riddle-1.5.11/lib/riddle/configuration/index.rb:29:in `block in render'
~/.rvm/gems/ruby-2.0.0-p451/gems/riddle-1.5.11/lib/riddle/configuration/index.rb:29:in `collect'
~/.rvm/gems/ruby-2.0.0-p451/gems/riddle-1.5.11/lib/riddle/configuration/index.rb:29:in `render'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/core/index.rb:53:in `render'
~/.rvm/gems/ruby-2.0.0-p451/gems/riddle-1.5.11/lib/riddle/configuration.rb:43:in `block in render'
~/.rvm/gems/ruby-2.0.0-p451/gems/riddle-1.5.11/lib/riddle/configuration.rb:43:in `collect'
~/.rvm/gems/ruby-2.0.0-p451/gems/riddle-1.5.11/lib/riddle/configuration.rb:43:in `render'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/configuration.rb:90:in `render'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/configuration.rb:96:in `block in render_to_file'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/configuration.rb:96:in `open'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/configuration.rb:96:in `render_to_file'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/rake_interface.rb:13:in `configure'
~/.rvm/gems/ruby-2.0.0-p451/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/tasks.rb:4:in `block (2 levels) in <top (required)>'
~/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => ts:configure
(See full trace by running task with --trace)
```

Seems like it conflicts with 'source' variable of vlad (https://github.com/seattlerb/vlad/blob/master/lib/vlad/subversion.rb#L3). If I disable vlad in my application, TS works completely fine.

**Comment by abartov** [comment]
A similar patch would be good in sql_builder/query.rb -- I am currently stuck with a legacy system using an old version of Vlad, and the same 'source' injection is a problem for me.  I have solved it manually by adding the source method as in 5d9106f9b602adfcc4f1e4e2d03039d900ab9436 but it would be good to have it in the standard gem.
