### ISSUE TITLE
Problem with FactoryGirl

### ISSUE THREAD

**Issue by danzanzini** [pat/thinking-sphinx#890]
Hi,

Today I've updated my ThinkingSphinx version from 2.0.14 to the most recent 3.1.3. (I'm in a process to update my rails app from 3.2 to 4)

I've made the changes and TS is working fine. But when I try to run my tests I got this error from the gem FactoryGirl: 

```
/home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/decorator/new_constructor.rb:9:in `new': undefined method `new' for ActiveRecord::Scoping::Default:Module (NoMethodError)
```

The gem was working fine until the update of the ThinkingSphinx gem.

Here is the full stacktrace

```
/home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/decorator/new_constructor.rb:9:in `new': undefined method `new' for ActiveRecord::Scoping::Default:Module (NoMethodError)
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/decorator.rb:14:in `send'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/decorator.rb:10:in `method_missing'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/decorator/invocation_tracker.rb:11:in `method_missing'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/decorator.rb:14:in `send'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/decorator.rb:10:in `method_missing'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/configuration.rb:15:in `block in initialize'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/attribute_assigner.rb:48:in `instance_exec'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/attribute_assigner.rb:48:in `build_class_instance'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/attribute_assigner.rb:13:in `object'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/evaluation.rb:12:in `object'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/strategy/build.rb:9:in `result'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/factory.rb:42:in `run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:161:in `instrument'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/factory_runner.rb:22:in `run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.2.0/lib/factory_girl/strategy_syntax_method_registrar.rb:19:in `block in define_singular_strategy_method'
	from /home/zanzini/dev/ISSIntel/spec/support/fixture_loader.rb:228:in `in_town_taxpayer'
	from /home/zanzini/dev/ISSIntel/spec/support/fixture_loader.rb:83:in `load_taxpayers!'
	from /home/zanzini/dev/ISSIntel/spec/support/fixture_loader.rb:24:in `reload_data!'
	from /home/zanzini/dev/ISSIntel/spec/spec_helper.rb:136:in `block (2 levels) in <top (required)>'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:21:in `instance_eval'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:21:in `run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:85:in `block in run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:85:in `each'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:85:in `run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:446:in `run_hook'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:27:in `block in run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:58:in `report'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:25:in `run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
	from /home/zanzini/.rvm/gems/ruby-2.1.5/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```

In `fixture_loader.rb:228` I just call a simple `FactoryGirl.create(:taxpayer)`
The model Taxpayer is indexed with TS.

Here is the index file of taxpayer `indices/taxapyer_index.rb`

```ruby
ThinkingSphinx::Index.define :taxpayer, with: :active_record,
  delta: true do

  indexes official_name, company_name, cpf_cnpj, address, address_zipcode,
          city_registration, state_registration, phone, email, search_digest,
          search_context, state

  has city_hall_id, accountant_id

  where "standalone = 0 AND state = 'approved' AND type <> 'Taxpayer::Merchant'"
end
```

Any thoughts on this problem?

**Comment by pat** [comment]
This is confusing, because there is *nothing* in that stack trace linked to Thinking Sphinx. Are there any other gems that were changed when you switched TS gem versions? Or is that hard to determine, given you're updating Rails versions and more?

**Comment by danzanzini** [comment]
Hi Pat, thanks for the response.

I'm updating one gem at a time to avoid problems. So the only gems I've update when the FactoryGirl broke was the ThinkingSphinx and its dependencies

```
+    innertube (1.1.0)
+    joiner (0.2.0)
+    middleware (0.1.0)
-    riddle (1.5.6)
+    riddle (1.5.11)
```

Even if I remove the indices folder the problem keeps happening.
I'm working on the problem, if I find out something useful I'll let you know.

**Comment by ArnisL** [comment]
I think i had something similar when i tried to use ruby 2.2.3

Downgraded to 2.1.2 and that solved it

Ain't 100% sure that was exact same problem.  
But it was factorygirl and activerecord related - couldn't start running tests
