### ISSUE TITLE
sql_attr_json support

### ISSUE THREAD

**Issue by lloeki** [pat/thinking-sphinx#894]
Sphinx supports [JSON attributes](http://sphinxsearch.com/docs/current/conf-sql-attr-json.html) (one level of nesting since 2.1, and any level since 2.2). Here are [more details](http://sphinxsearch.com/blog/2013/08/08/full-json-support-in-trunk/), notably SphinxQL syntax.

I saw no mention of this in Thinking Sphinx's documentation.

**Comment by pat** [comment]
It _should_ be in the documentation (patches welcome!), because it _should_ work - columns with a JSON type should be translated to sql_attr_json when used as attributes (which is supported explicitly in recent Riddle versions, and that support should carry across implicitly for Thinking Sphinx).

If you're finding this isn't the case though, do let me know!

**Comment by andrewcarpenter** [comment]
I get errors when I try to add a `type: :json` attribute:

```rake aborted!
NoMethodError: undefined method `<<' for nil:NilClass
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/active_record/sql_source.rb:95:in `block in append_presenter_to_attribute_array'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/active_record/sql_source.rb:93:in `each'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/active_record/sql_source.rb:93:in `append_presenter_to_attribute_array'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/active_record/sql_source.rb:131:in `prepare_for_render'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/active_record/sql_source.rb:65:in `render'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/riddle-1.5.11/lib/riddle/configuration/index.rb:29:in `block in render'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/riddle-1.5.11/lib/riddle/configuration/index.rb:29:in `collect'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/riddle-1.5.11/lib/riddle/configuration/index.rb:29:in `render'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/core/index.rb:58:in `render'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/riddle-1.5.11/lib/riddle/configuration.rb:43:in `block in render'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/riddle-1.5.11/lib/riddle/configuration.rb:43:in `collect'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/riddle-1.5.11/lib/riddle/configuration.rb:43:in `render'
/Users/andrewcarpenter/Documents/CMQCC/datacenter/config/initializers/thinking_sphinx.rb:43:in `render_with_ruby_eval'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/configuration.rb:93:in `render'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/configuration.rb:99:in `block in render_to_file'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/configuration.rb:99:in `render_to_file'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/rake_interface.rb:24:in `configure'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/tasks.rb:4:in `block (2 levels) in <top (required)>'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/andrewcarpenter/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => ts:configure```

I can resolve it by adding the following in an initializer:

`ThinkingSphinx::ActiveRecord::Attribute::SphinxPresenter::SPHINX_TYPES[:json] = :json`

and then everything runs ok and I can use the JSON attributes.

**Comment by pat** [comment]
Thanks Andrew - that patch is in the `develop` branch, which you can use right now if you'd like. Otherwise, it'll be part of the next TS release.
