### ISSUE TITLE
Using hstore keys as attributes rather than indices?

### ISSUE THREAD

**Issue by ben-eb** [pat/thinking-sphinx#959]
Hello, thanks for this really useful gem. :smile:

I was wondering if it's possible to use `has` in combination with PostgreSQL hstore fields? I can do indices with this:

```ruby
ThinkingSphinx::Index.define :model, with: :active_record do
  Model.features.each do |key|
    indexes "features -> '#{key}'", as: key.to_sym
  end
end
```

However, I get an exception when changing `indexes` to `has`.

```
ThinkingSphinx::MissingColumnError: column features->'image' does not exist
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/type.rb:74:in `type_from_database'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/type.rb:17:in `type'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute.rb:4:in `type'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/sphinx_presenter.rb:31:in `sphinx_type'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/sphinx_presenter.rb:19:in `collection_type'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:96:in `block in append_presenter_to_attribute_array'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:93:in `each'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:93:in `append_presenter_to_attribute_array'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:131:in `prepare_for_render'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:65:in `render'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/riddle-1.5.12/lib/riddle/configuration/index.rb:29:in `block in render'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/riddle-1.5.12/lib/riddle/configuration/index.rb:29:in `collect'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/riddle-1.5.12/lib/riddle/configuration/index.rb:29:in `render'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/core/index.rb:57:in `render'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/riddle-1.5.12/lib/riddle/configuration.rb:43:in `block in render'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/riddle-1.5.12/lib/riddle/configuration.rb:43:in `collect'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/riddle-1.5.12/lib/riddle/configuration.rb:43:in `render'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:93:in `render'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:99:in `block in render_to_file'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:99:in `render_to_file'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:24:in `configure'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:35:in `index'
/Users/beneb/.rvm/gems/ruby-2.2.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/tasks.rb:9:in `block (2 levels) in <top (required)>'
/Users/beneb/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/beneb/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Any advice would be appreciated!

**Comment by pat** [comment]
Hi Ben

Given you're not referring to a column, the type cannot be determined automatically, so you'll need to specify it as part of the attribute definition, using the `type` option.

```has "features -> 'image'", as: :image, type: :string```

Given you've got a bit of meta-programming happening there, you may need to change things more deeply so your features have a corresponding type (unless they're all the same type?).

**Comment by ben-eb** [comment]
Hi Pat,

Thanks for the fast response! You're right, it seems a bit more involved than I thought too. hstore is stored as simple key/value pairs, where *everything* is a string. That's not a problem at the application level because the [types are coerced](https://github.com/solnic/virtus), but it seems like a problem at the Sphinx level because I can't seem to filter results by the attributes.

```ruby
collection = Model.search(
  params[:q],
  with: {
    cost: 400..500
  }
)
```

Even with my hacky attempt at trying to specify the column type:

```ruby
ThinkingSphinx::Index.define :model, with: :active_record do
  Model.features.each do |key|
    if key === 'cost'
      has "features -> '#{key}'", type: :integer, as: key.to_sym
    else
      has "features -> '#{key}'", type: :string, as: key.to_sym
    end
  end
end
```

I'm not sure how best to approach this or even if this is an idiomatic way of doing this. :smile:

**Comment by pat** [comment]
It's certainly getting a bit hackish, but what you could try is casting the value within the SQL snippet:

```ruby
ThinkingSphinx::Index.define :model, with: :active_record do
  Model.features.each do |key|
    if key === 'cost'
      has "(features -> '#{key}')::int", type: :integer, as: key.to_sym
    else
      has "features -> '#{key}'", type: :string, as: key.to_sym
    end
  end
end
```

**Comment by ben-eb** [comment]
As it turns out my ruby foo needs some work, those keys are symbols and not strings. Too much JS!

Thanks a lot, Pat. :+1:
