### ISSUE TITLE
Error on Ruby 2.3.0 and 2.3.1

### ISSUE THREAD

**Issue by vanderhoorn** [pat/thinking-sphinx#989]
I see the following stack trace on Ruby 2.3.x. Glance Search is an internal gem that requires Thinking Sphinx. It doesn't change anything in Thinking Sphinx itself. The error is present when using Thinking Sphinx 3.0.x or 3.1.x. I haven't tried 3.2.x, but the relevant code appears the same.

If I switch back to Ruby 2.2.x the error is gone and it works perfectly. Any clue?

```
$ bundle exec rake db:migrate RAILS_ENV=test
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'glance_search'.
Gem Load Error is: undefined method `!' for class `ThinkingSphinx::Search'
Did you mean?  !
               !=
               !~
Backtrace for gem load error is:
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:18:in `undef_method'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:18:in `block in <class:Search>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:17:in `each'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:17:in `<class:Search>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:1:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx.rb:63:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/glance_search-2.0.0/lib/glance_search.rb:2:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/Users/vanderhoorn/projects/sbrwebsite/config/application.rb:7:in `<top (required)>'
/Users/vanderhoorn/projects/sbrwebsite/Rakefile:5:in `require'
/Users/vanderhoorn/projects/sbrwebsite/Rakefile:5:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/bin/rake:23:in `load'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/bin/rake:23:in `<main>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/Users/vanderhoorn/projects/sbrwebsite/config/application.rb:7:in `<top (required)>'
/Users/vanderhoorn/projects/sbrwebsite/Rakefile:5:in `require'
/Users/vanderhoorn/projects/sbrwebsite/Rakefile:5:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
NameError: undefined method `!' for class `ThinkingSphinx::Search'
Did you mean?  !
               !=
               !~
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:18:in `undef_method'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:18:in `block in <class:Search>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:17:in `each'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:17:in `<class:Search>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx/search.rb:1:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/thinking-sphinx-3.0.6/lib/thinking_sphinx.rb:63:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/glance_search-2.0.0/lib/glance_search.rb:2:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/Users/vanderhoorn/projects/sbrwebsite/config/application.rb:7:in `<top (required)>'
/Users/vanderhoorn/projects/sbrwebsite/Rakefile:5:in `require'
/Users/vanderhoorn/projects/sbrwebsite/Rakefile:5:in `<top (required)>'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/vanderhoorn/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by pat** [comment]
Hrm. This is odd. I've just run some of the TS specs in both Ruby 2.3.0 and 2.3.1, checking TS v3.0.6, 3.1.4 and 3.2.0, and in all cases the above error does not occur. And indeed, just running `require 'thinking-sphinx'` in both versions of ruby is also fine. Does the latter work for you?

**Comment by vanderhoorn** [comment]
I've tried to isolate the problem to be able to reproduce it, but no luck so far.

The project runs Rails 3.2.22.2. It works fine on Ruby 2.1 and 2.2, but not on Ruby 2.3.
In the glance_search gem it just works (tried with Rails 3.2.22.2 and Rails 4.2).

I'll investigate further.

**Comment by vanderhoorn** [comment]
It has something to do with the order in which things are loaded. If I add ```require 'thinking-sphinx'``` early in ```application.rb``` i don't get the error.

**Comment by vanderhoorn** [comment]
I'm getting somewhere. It appears to be a problem with the shoulda-context gem (tried version 1.1.6 and 1.2.1). If I remove that gem then it just works.

Not sure what that gem does that makes it go wrong, but I guess it's time to replace it. Sorry for the fuss.

**Comment by jordoh** [comment]
I'm seeing this same exception on ruby 2.3.3 when the power_assert gem has been required (it's a dependency of test-unit). This appears to be a side-effect of the way power_assert uses refinements.

This line in power_assert adds a refinement to `Array` for the `!` method (among other methods):
https://github.com/k-tsj/power_assert/blob/master/lib/power_assert/enable_tracepoint_events.rb#L46

Commenting out this line fixes the exception listed in the original report.

I can reproduce this with a simple case in irb:

```
> irb
2.3.3 :001 > class SomeClass < Array
2.3.3 :002?>   end
nil
2.3.3 :003 > SomeClass.send(:undef_method, :!)
SomeClass < Array
```
vs. what power_assert does:
```
> irb
2.3.3 :001 > module SomeModule
2.3.3 :002?>     refine Array do
2.3.3 :003 >           define_method(:!) {}
2.3.3 :004?>       end
2.3.3 :005?>   end
#<refinement:Array@SomeModule>
2.3.3 :006 > 
2.3.3 :007 >   class SomeClass < Array
2.3.3 :008?>   end
nil
2.3.3 :009 > 
2.3.3 :010 >   SomeClass.send(:undef_method, :!)
NameError: undefined method `!' for class `SomeClass'
Did you mean?  !
               !=
               !~
	from (irb):10:in `undef_method'
	from (irb):10
	from /home/jordan/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'
```

**Comment by jordoh** [comment]
It looks like a fix for this will be in the next 2.3.x release: https://bugs.ruby-lang.org/issues/13096

**Comment by pat** [comment]
I'll take some solace in the fact that it's a Ruby bug. If anyone wants to sort out a workaround I'm open to patches, but also very happy to just wait for the new 2.3.x release - hopefully not many other gems/apps use refinements on Array!

**Comment by jordoh** [comment]
Well, that was timely: I can confirm that ruby 2.3.4 contains the fix for this.

https://github.com/ruby/ruby/commit/f8e37f5771e20ee532e14d2878a93618e6ba4d96
